export const sampleStops = [
  {
    id: 'sample-1',
    customerName: 'Adams Family',
    address: '101 Liberty Lane',
    lat: 29.7604,
    lng: -95.3698,
    instructions: 'Place near mailbox.',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
  {
    id: 'sample-2',
    customerName: 'Baker Family',
    address: '205 Eagle Drive',
    lat: 29.765,
    lng: -95.375,
    instructions: 'Avoid sprinkler head.',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
  {
    id: 'sample-3',
    customerName: 'Clark Family',
    address: '309 Scout Trail',
    lat: 29.752,
    lng: -95.361,
    instructions: '',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
  {
    id: 'sample-4',
    customerName: 'Davis Family',
    address: '412 Patriot Court',
    lat: 29.771,
    lng: -95.382,
    instructions: 'Gate code in coordinator notes.',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
  {
    id: 'sample-5',
    customerName: 'Evans Family',
    address: '518 Troop Way',
    lat: 29.749,
    lng: -95.388,
    instructions: '',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
  {
    id: 'sample-6',
    customerName: 'Flores Family',
    address: '622 Honor Street',
    lat: 29.781,
    lng: -95.35,
    instructions: 'Flag tube by oak tree.',
    posted: false,
    pickedUp: false,
    postedAt: '',
    pickedUpAt: '',
    comment: '',
  },
]
